version: '3.8'

services:
  neo4j-db1:
    image: neo4j:5.17-community
    container_name: neo4j-db1
    ports:
      - '7474:7474' # HTTP
      - '7687:7687' # Bolt
    environment:
      - NEO4J_AUTH=neo4j/testpass1
    volumes:
      - neo4j-db1-data:/data

  neo4j-db2:
    image: neo4j:5.17-community
    container_name: neo4j-db2
    ports:
      - '7475:7474'
      - '7688:7687'
    environment:
      - NEO4J_AUTH=neo4j/testpass2
    volumes:
      - neo4j-db2-data:/data

  neo4j-db3:
    image: neo4j:5.17-community
    container_name: neo4j-db3
    ports:
      - '7476:7474'
      - '7689:7687'
    environment:
      - NEO4J_AUTH=neo4j/testpass3
    volumes:
      - neo4j-db3-data:/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000' # S3 API
      - '9001:9001' # MinIO Console
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest # Correct image name
    container_name: chromadb
    ports:
      - '5002:8000' # Changed port mapping from 5000 to 5002
    volumes:
      - ./chroma-data:/chroma_data # Persist ChromaDB data locally
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=http://localhost:3000 # Adjust if needed for your frontend app
    restart: unless-stopped

volumes:
  neo4j-db1-data:
  neo4j-db2-data:
  neo4j-db3-data:
  minio-data:
  # chroma-data:
